version: '3.8'
services:
  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.3
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      ETCD_USE_EMBED: "true"
      MINIO_USE_EMBED: "true"
      PULSAR_USE_EMBED: "true"

  attu:
    container_name: attu
    image: zilliz/attu:v2.2.3
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "8003:3000"
    depends_on:
      - milvus-standalone

      


volumes:
  milvus_data:

